server:
  port: 8085
  servlet:
    context-path: /boot
spring:
#数据源配置
  datasource:
    url: jdbc:mysql://120.79.4.109:3306/sboot?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    #com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: detect
  #redis配置文件
  redis:
    host: 120.79.4.109
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 20
        min-idle: 8
    timeout: 0

mybatis:
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.lyl.pojo
  mapper-locations: classpath:mapper/*.xml

#配置日志
debug: false

